name: random-bridge-ea
description: An external adapter to get randomness from drand.love.
node_identifier: hicetnunc2000#2
platforms:
  - AWS Lambda
data_sources:
  - name: random_bridge
    url: https://58ln53fooe.execute-api.us-east-1.amazonaws.com/dev/random_bridge
parameters:
